product: rocky8
full_name: Rocky Linux 8
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

pkg_release: "60287f36"
pkg_version: "6d745a60"
#aux_pkg_release: "AUX_PKG_RELEASE"
#aux_pkg_version: "AUX_PKG_VERSION"

#release_key_fingerprint: "RELEASE_KEY_FINGERPRINT"
#auxiliary_key_fingerprint: "AUXILIARY_KEY_FINGERPRINT"
oval_feed_url: "https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml"

cpes_root: "../shared/applicability"
cpes:
  - rhel8:
      name: "cpe:/o:rocky:rocky:8"
      title: "Rocky Linux 8"
      check_id: installed_OS_is_rocky8

# Mapping of CPE platform to package
platform_package_overrides:
  login_defs: "shadow-utils"
