product: rocky8
full_name: Rocky Linux 8
type: platform

benchmark_root: "../../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

pkg_release: "60287f36"
pkg_version: "6d745a60"
rocky_pkg_release: "60287f36"
rocky_pkg_version: "6d745a60"

rocky_major_version: "8"

oval_feed_url: "https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml"

grub2_uefi_boot_path: "/boot/efi/EFI/redhat"

cpes_root: "../../shared/applicability"
cpes:
  - rocky8:
      name: "cpe:/o:rocky:rocky:8"
      title: "Rocky Linux 8"
      check_id: installed_OS_is_rocky8

# Mapping of CPE platform to package
platform_package_overrides:
  login_defs: "shadow-utils"
